version: '3'
services:
  postgresql:
    container_name: biotis_postgresql
    image: postgres
    ports:
      - "15432:5432"
    environment:
      POSTGRES_DB: biotisst_db
      POSTGRES_USER: biotisst_admin
      POSTGRES_PASSWORD: biotisst_password